services:
  backend:
    env_file:
      - .env
    container_name: star-vector-api
    image: star-vector-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python3 main.py"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - star-vector-network

networks:
  star-vector-network:
    driver: bridge
